'use strict'; // code generated by pbf v3.1.0

var StreamProfile = exports.StreamProfile = {
    "AUDIO_AAC": 3,
    "AUDIO_SPEEX": 4,
    "AUDIO_OPUS": 5,
    "VIDEO_H264_50KBIT_L12": 6,
    "VIDEO_H264_530KBIT_L31": 7,
    "VIDEO_H264_100KBIT_L30": 8,
    "VIDEO_H264_2MBIT_L40": 9,
    "VIDEO_H264_50KBIT_L12_THUMBNAIL": 10,
    "META": 11,
    "DIRECTORS_CUT": 12,
    "AVPROFILE_MOBILE_1": 1,
    "AVPROFILE_HD_MAIN_1": 2
};
